# version: '3.8'

services:
  web:
    build: .
    container_name: crud-app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - .:/crud
      - ./migrations:/crud/migrations    # ðŸ‘ˆ mount migrations folder
    #   - ./alembic.ini:/crud/alembic.ini  # ðŸ‘ˆ optional but recommended
    depends_on:
      - db
    #   - redis
    # environment:
    #   - DATABASE_URL=postgresql://postgres:Tkpostsql@db:5432/splitwisedb
    #   - REDIS_URL=redis://redis:6379
    #   - JWT_SECRET=supersecretkey
    #   - JWT_ALGORITHM=HS256
    #   - ACCESS_TOKEN_EXPIRE_MINUTES=30
    #   - ENV PYTHONUNBUFFERED=1

  db:
    image: postgres:15
    container_name: crud_db
    restart: always
    environment:
      POSTGRES_DB: cruddb        # âœ… Your DB name
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Tkpostsql
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin44
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

  # redis:
  #   image: redis:7
  #   container_name: redis-cache
  #   ports:
  #     - "6379:6379"

volumes:
  postgres_data:
  pgadmin_data:
